### PR TITLE
api: add rootfs-image.version to fix device display

### PR DESCRIPTION
**Pull request by joelguittet**
The purpose of this Pull-Request is to fix the "Current software" display on mender interface. This issue was reported at https://github.com/joelguittet/mender-mcu-client/issues/69

### CODE REVIEW

**Comment by joelguittet** [comment]
@lluiscampos if you want to check it before I merge the fix, here it is! As discussed in the issue, this is a quick fix to ensure the display of the software version. Not sure if this make sense to separate version and artifact_name, neither to add rootfs checksum ? What is your opinion ?

Note: on MCU the checksum of the image is changing when the image is validated by the bootloader. This is why I say it has not a good value to be reported.

**Review by lluiscampos — APPROVED** [review]
Looks good!

**Comment by lluiscampos** [comment]
> @lluiscampos if you want to check it before I merge the fix, here it is! As discussed in the issue, this is a quick fix to ensure the display of the software version

Taking into account the MCU client capabilities, this is good enough.

> Not sure if this make sense to separate version and artifact_name, neither to add rootfs checksum ? What is your opinion ?

It is harmless as it is, but `artifact_name` could be removed in order to save few bytes.

The checksum does not make sense as long as the MCU client does not support provides/depends (iow deployments v2 POST deployments/next), where the checksum together with other attributes could be used for the server to select one or other Artifact.

> 
> Note: on MCU the checksum of the image is changing when the image is validated by the bootloader. This is why I say it has not a good value to be reported.

This is a details that I didn't know! Thanks for pointing it out.

**Comment by joelguittet** [comment]
Thanks for looking at this @lluiscampos ! yes it will always be possible to enhance later if required to separate artifact name and software version :-)

The point about the checksum is because of the confirmation of the image done when the update is validated. Flag set at this moment in the trailer of the slot. This is an important point when thinking to delta update, something I have already think about and I would like to propose solutions ;-) or maybe mender will do it !

**Pull request merged**
