### PR TITLE
Add deployment available hook

### PR DESCRIPTION
**Pull request by stephendpmurphy**
This PR adds the ability to notify the integrating application of a deployment and gives it an opportunity to proceed or postpone the update.

This is building on changes in PR #16 that we are still working on getting completed. Setting to a Draft PR for now. Let me know if you need anything further added or updated. @joelguittet

### CODE REVIEW

**Comment by joelguittet** [comment]
Hello @stephendpmurphy 

This is not bad, I was just thinking to something closed to this: adding a callback to indicate deployment checking has been done and system is up to date, just to inform the app mender client is alive and it is properly checking for deployment.

By the way this "deployment_available" callback is interesting. My initial approach was to download the artifact asap and then you can reboot or not when the reboot callback is called. But this second option is fine.

I added few comments, that's clearly details, I agree with the global approach and implementation. I would like to add 2 requests please: separate the PR (http on one side, deployment status on the other side), and short commit description "client: <description>", for example "client: introduce deployment status callback" will be enough (I known I should add developers guidelines etc to the project, nothing against you, this is just to keep something consistent and clean across time!)

Joel

**Comment by stephendpmurphy** [comment]
Hi @joelguittet 

The reason for this approach is that the act of downloading the artifact into flash was causing latency in our application that was noticeable by a user. So with this approach we are able to make the app aware of an update (and the version), take note that it needs to do an OTA, and then wait until a later time to actually follow through.

I'll work on getting this split out into it's own PR (and accompanying commits).

Thanks!

**Comment by joelguittet** [comment]
@stephendpmurphy I have just notice your commit 57b5be2d3d35603507892c614f6182a235bee7fc, this is known issue for me so I'm not surprised at the moment :-) 

Not corrected at this time because not sure of the correction. You added a boolean flag, this is one solution. What about giving the semaphore when it is created instead of when the work is activated ? I mean in your use case, does it solve the issue ?

**Comment by stephendpmurphy** [comment]
> @stephendpmurphy I have just notice your commit 57b5be2d3d35603507892c614f6182a235bee7fc, this is known issue for me so I'm not surprised at the moment :-) 
> 
> 
> 
> Not corrected at this time because not sure of the correction. You added a boolean flag, this is one solution. What about giving the semaphore when it is created instead of when the work is activated ? I mean in your use case, does it solve the issue ?

That's completely fine by me. I'm in a bit of a crunch and honestly didn't have time to fully vet that change to make sure it didn't have adverse effects so I created a new flag. I'll take the semaphore at worker creation 👍

I also plan to separate these out into individual commits and PRs I just need to get some things working on my current branch. Sorry!

**Comment by joelguittet** [comment]
Good if you can confirm this is working on your side just moving the give call. In fact this is just changing the initial state of the semaphore.

No problem with the current state, I m working on another part on my side ;-) and I m happy to see people using this library and contributing. Do it clean when you have the time to do so :-)

**Pull request closed without merging**
