### PR TITLE
Update code format with newer `clang-format` tool

### PR DESCRIPTION
**Pull request by lluiscampos**
Ubuntu 20.04 used in CI was getting a bit dated.

Updated CI job with latest Ubuntu LTS release (with newer `clang-format`) and format all the code accordingly.

### CODE REVIEW

**Comment by lluiscampos** [comment]
Hi @joelguittet, I hope that you don't find this PR too intrusive. What do you think about updating the tool?

**Review by joelguittet — COMMENTED** [review]
This is a large PR but looks good improvement for readability of the code. To be honest I don't know why it was not properly aligned with the previous clang version...
Can you simply rebase on top of the master branch so that we keep a clean git history ? Thanks

**Comment by joelguittet** [comment]
Additionally if possible can you update the commit title to something like "ci : xxx". I see you do that for other mender stuff such as https://github.com/mendersoftware/meta-mender/commit/bf90a127145eb9de59d73d7586fadbd6922440fc. This is not a strong rule but I think it can help in the future to easily grep the git log, just in case we need. Thanks a lot!
Note: I see you have also the good habit to make a good comment and the sign off in the commit 👍

**Comment by lluiscampos** [comment]
Thanks @joelguittet 

> (...). Can you simply rebase on top of the master branch so that we keep a clean git history ? Thanks

Done

> Additionally if possible can you update the commit title to something like "ci : xxx". I see you do that for other mender stuff (...) 

Done. Although I decided to use `style`.

In Mender we require Conventional Commits formatting (you can see the spec [here](https://www.conventionalcommits.org/en/v1.0.0/)) but I try to follow the existing commit style when I contribute to Open Source projects, so I didn't want to "impose" that here. However I am happy to see that you see value on it!

**Comment by joelguittet** [comment]
Thanks and a gig sorry, I will ask you to rebase again :-( I have reverted the deployment api modification in the meantime.
The title is fine for me!

**Comment by lluiscampos** [comment]
> Thanks and a gig sorry, I will ask you to rebase again

Rebased now.

Sorry to be slow - I am on vacation and I do GitHub only on bad weather days :umbrella:

**Review by joelguittet — APPROVED** [review]

**Comment by joelguittet** [comment]
All good for me @lluiscampos, thanks for the updates! Merging now.

**Pull request merged**
